name: flutter_core_modules
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  hooks_riverpod: ^3.0.0
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.1
  webview_all: ^0.5.2
  intl: ^0.20.2
  async: ^2.13.0
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  fluttertoast: ^8.2.12
  in_app_review: ^2.0.11
  purchases_ui_flutter: ^9.5.0
  ios_design_system:
    git:
      url: https://github.com/sampaio-tech/iOS-design-system.git
      ref: main
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  wakelock_plus: ^1.3.2
  purchases_flutter: ^9.5.0
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_remote_config: ^6.0.1
  firebase_crashlytics: ^5.0.1
  riverpod: ^3.0.0
  app_settings: ^6.1.1
  flutter_dotenv: ^6.0.0
  statsig: ^1.2.6
  mixpanel_flutter: ^2.4.4
  posthog_flutter: ^5.4.3
  sizer: ^3.1.3
  flutter_native_splash: ^2.4.6
  amplitude_flutter: ^4.3.7
  clarity_flutter: ^1.4.0
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  df_generate_dart_indexes: ^0.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
